### ISSUE TITLE
Support tests that return `Result<T, E>`

### ISSUE THREAD

**Issue by ThatGeoGuy** [smol-rs/smol-macros#6]
First off: thanks for the crate, it makes getting started writing tests pretty easy to work with.

In regular (standard, not async) Rust we can do:

```rust
#[cfg(test)]
mod tests {
    use super::*;
    use std::error::Error;

    #[test]
    fn it_works() -> Result<(), Box<dyn Error>> {
        let _ = f32::try_from(20usize)?;
        Ok(())
    }
}
```

However, the `test!` macro doesn't support this form at all, and assumes that all tests return `()`. 

This means that we can't write:

```rust
#[cfg(test)]
mod tests {
    use super::*;
    macro_rules_attribute::apply;
    use std::error::Error;

    #[apply(smol_macros::test!]
    async fn it_works(_ex: &Executor<'_>) -> Result<(), Box<dyn Error>> {
        let _ = f32::try_from(20usize)?;
        Ok(())
    }
}
```

The current workaround to this is to just `.unwrap` or `.expect` all `Result` types in the function. Materially, they don't really change the logic of the test (since a panic means failure), but it is often nice to be able to write the code with `?` and `FromResidual` only because the tests can often serve as an example for how code should be written in practice.

Thoughts? Would the current macro be able to be reworked so that the return type for a test can be set as well?

**Comment by notgull** [comment]
I would accept a PR for this.

**Comment by notgull** [comment]
I submitted #6 to test this issue. However, it looks like tests that return `Result` already work?

```rust
#[apply(test!)]
async fn it_works(_ex: &Executor<'_>) -> Result<(), Box<dyn std::error::Error>> {
    let _ = u32::try_from(20usize)?;
    Ok(())
}
```

**Comment by ThatGeoGuy** [comment]
I do recall testing the example I pasted, and it did not work. Perhaps there was some update in the meantime that allowed for this? I believe I was testing on 1.75.0, but if it works now I'd be happy to close this.

**Comment by notgull** [comment]
I doubt it. The MSRV tests on 1.63, so unless the bug was introduced and then fixed at some point between then and now it wouldn't make sense.

**Comment by ThatGeoGuy** [comment]
Huh. Well, I'll go ahead and close. Appears that I was mistaken and I apologize for the churn. I could swear I had this failing but very clearly that test passes.
